version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${EMA_API_DATABASE_USERNAME:-ema_user}
      POSTGRES_PASSWORD: ${EMA_API_DATABASE_PASSWORD:-password}
      POSTGRES_DB: ema_api_development
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${EMA_API_DATABASE_USERNAME:-ema_user}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ema_api_development
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SOLID_QUEUE_ENABLED=true

  solid_queue:
    build: .
    command: bundle exec solid_queue --config-file=config/solid_queue.yml
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ema_api_development
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  # redis_data:
  bundle_cache:
  gem_cache:
